# ...existing code...
version: '3.8'
services:
  db:
    image: mysql:5.7
    env_file:
      - .env.prod
    environment:
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - appnet

  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    env_file:
      - .env.prod
    environment:
      APP_ENV: "${APP_ENV}"
      APP_SECRET: "${APP_SECRET}"
      DATABASE_URL: "${DATABASE_URL}"
    volumes:
      - ./:/var/www/html
    expose:
      - "9000"
    depends_on:
      - db
    networks:
      - appnet

  nginx:
    image: nginx:stable
    env_file:
      - .env.prod
    ports:
      - "${NGINX_HTTP_PORT:-80}:80"
      - "${NGINX_HTTPS_PORT:-443}:443"
    volumes:
      - ./:/var/www/html:ro
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - php
    networks:
      - appnet

volumes:
  db_data:

networks:
  appnet:
# ...existing code...